### ISSUE TITLE
Cannot find module 'moment-guess' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by amcdnl** [apoorv-mishra/moment-guess#6]
VSCode is showing this error:

```
Cannot find module 'moment-guess' or its corresponding type declarations.ts(2307)
```

with versions:

```
    "moment": "^2.27.0",
    "moment-guess": "^1.1.1",
```

![image](https://user-images.githubusercontent.com/227909/98704530-c1beef80-234a-11eb-9060-435f37827edd.png)

**Comment by apoorv-mishra** [comment]
Hi @amcdnl, it's so because `moment-guess` is not intended to be used as a module(there's no *main* field in `package.json`, therefore you can't *require/import* it!). It's supposed to be used as a CLI utility. Kindly check its usage at https://github.com/apoorv-mishra/moment-guess#-usage

Thanks for reporting.

**Comment by amcdnl** [comment]
Oh - well thats sad - its a very useful package. I'm using an older version that I was able to get this to import as.

**Comment by apoorv-mishra** [comment]
I see. Sorry for that. I wasn't expecting it since I never mentioned or encouraged anywhere in the docs to use it as a module :sweat_smile: 

Based on discussions with fellow developers, I found that they were more comfortable using it as a CLI utility rather than as a module, therefore I decided to drop support for the latter(this also helped reduce the bundled size).

Anyways, I'll keep the issue open as it might be later decided to add back the support for using `moment-guess` as a module. Till then, I would suggest you to downgrade it to `1.0.10` to avoid breaking your code. Unfortunately, you won't be getting new features.

**Comment by buonzz** [comment]
but how about us who needs it as a module...

**Comment by apoorv-mishra** [comment]
Hi @buonzz , it will be added soon in the next release probably.

**Comment by apoorv-mishra** [comment]
As of `moment-guess@1.1.2`, one can use it as a module via *require/import* syntax. @amcdnl @buonzz

**Comment by W4G1** [comment]
Still getting this error with version 1.2.4
